### ISSUE TITLE
Support for some way to include another apib file

### ISSUE THREAD

**Issue by joan38** [subosito/snowboard#1]
Hey,

Is there any way to do an include like for Aglio:
```
<!-- include(badgeCount.apib) -->
```
See: https://github.com/danielgtaylor/aglio#including-files

Cheers

**Comment by subosito** [comment]
Hi @joan38, thanks for asking.

Just finished working on it. You can download [v0.3.2](https://github.com/subosito/snowboard/releases/tag/v0.3.2) which have partials support.

The syntax is bit different, hope you don't mind :)

```
{{partial "badgeCount.apib"}}
```

**Comment by subosito** [comment]
Hi @joan38. I am here for new updates.

Just published a new version [v0.3.3](https://github.com/subosito/snowboard/releases/tag/v0.3.3) which adds support for including file using HTML comment, just like what you mention about.

So, now you have two ways for including file:

```
{{partial "badgeCount.apib"}}
```

or 

```
<!-- include(badgeCount.apib) -->
```

**Comment by joan38** [comment]
Hi @subosito,

That looks nice.
Both syntax are great.

Feel free to close this ticket then.

Thanks a lot

**Comment by nbob** [comment]
But `partial` does not work in apib-file included by `partial` func.
Need a fix.
