### ISSUE TITLE
Mock server response is always a 404

### ISSUE THREAD

**Issue by shadowhand** [subosito/snowboard#21]
Partial copy of my API Blueprint:

```apib
## Group Collection [/groups?{onlyRemote}]

### List all active Groups [GET]

+ Parameters
    - onlyRemote (optional, boolean) - Only include groups with remote mappings
      - Default: false

+ Response 200 (application/json)
    - Attributes
        - data (array[Group])
```

I start the mock server using:

```
$ snowboard mock -i api-description.apib
Mock server is ready. Use 127.0.0.1:8087
Available Routes:
GET     200     groups/:id
POST    201     groups/:id
GET     200     groups?:onlyRemote
GET     200     rosters/:id
GET     200     rosters
```

And every request results in a 404:

```
$ curl -i "http://127.0.0.1:8087/rosters"
HTTP/1.1 404 Not Found
Date: Tue, 11 Apr 2017 20:30:45 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

**Comment by subosito** [comment]
Hi @shadowhand, I Just published a fix for this issue. You can upgrade snowboard to `v0.6.2`.

**Comment by shadowhand** [comment]
Still getting 404s for every URL after upgrading.

**Comment by subosito** [comment]
That's strange. Can you post sample api blueprint? So I can try to reproduce here.

**Comment by shadowhand** [comment]
FORMAT: 1A
HOST: https://api.acme.net/

# Acme

The complete API for Acme application.

## Group Patient Groups

Resources related to patient groups.

## Group [/groups/{id}]

+ Attributes
    - id: 1 (number)
    - name: Segment 1 (string, required)
    - remote_id: ABCD (string, nullable)

+ Parameters
    - id: 1 (number) - Group identifier

### Fetch a Group [GET]

+ Response 200 (application/json)
    - Attributes
        - data (Group)

### Create a Group [POST]

+ Request (application/json)
    - Attributes (Group Create)

+ Response 201 (application/json)
    - Attributes 
        - data (Group Created)

## Group Collection [/groups?{onlyRemote}]

### List all active Groups [GET]

+ Parameters
    - onlyRemote (optional, boolean) - Only include groups with remote mappings
      - Default: false

+ Response 200 (application/json)
    - Attributes
        - data (array[Group])

## Group Patient Rosters

Resources related to patient rosters.

## Roster [/rosters/{id}]

+ Attributes
    - id: 1 (number, required)
    - name: North Region (string, required)

+ Parameters
    - id: 1 (number) - Roster identifier

### Fetch a Roster [GET]

+ Response 200 (application/json)
    - Attributes
        - data (Roster)

## Roster Collection [/rosters]

### List all available Rosters [GET]

+ Response 200 (application/json)
    - Attributes
        - data (array[Roster])


## Data Structures

### Group Create (object)

- name: Segment 2 (string, required)
- remote_id (nullable, optional)

### Group Created (object)

- id: 2 (number)
- Include Group Create
```

**Comment by shadowhand** [comment]
@subosito ^ see gist.

**Comment by subosito** [comment]
Hi @shadowhand can you test using https://github.com/subosito/snowboard/commit/f160439551d8804902a74a34b0b9b3a91d65d0e5 ?

There is an issue with url path resolution, so:

```
# previously
-----------------------
HOST: https://api.acme.net/
## Group [/groups/{id}]
===> will produce: groups/:id (which unfortunately not working)

to make it work:

HOST: https://api.acme.net <- no trailing slash
## Group [/groups/{id}]
===> will produce: /groups/:id (it's working)
```

The commit fixes above issue. So both `HOST` with trailing and without trailing slash will be handled properly.

Going to push a new release soon.

**Comment by shadowhand** [comment]
@subosito can I run it locally with docker somehow? I don't have Go installed on this machine.

**Comment by subosito** [comment]
Sure, you can use docker. Docker image is always pointing to master.

**Comment by shadowhand** [comment]
@subosito well, I'm not Docker expert. I managed to get it built and started, but I can't figure out how to connect to it. I assumed I would be able to do:

```
docker build -t snowboard .
docker run -it --rm -v $PWD:/doc snowboard mock -i api-description.apib
open "http://$(docker-machine ip):8087/rosters"
```

But no 🎲 , fails to to connect. Any idea what I am doing wrong?

**Comment by subosito** [comment]
@shadowhand You need to let snowboard binding to `0.0.0.0` so it can be accessed on docker host. You can try following:

```
docker run -it --rm -v $PWD:/doc -p 8087:8087 snowboard mock -b 0.0.0.0:8087 -i api-description.apib
open "http://$(docker-machine ip):8087/rosters"
```

**Comment by shadowhand** [comment]
@subosito perfect, that did the trick. I have confirmed that this is working as expected now!

**Comment by manishekarreddy** [comment]
I have the Same 404 issue (not using the trailing slash)
Just using an index.html and app.js with AJAX 'GET' Method
