### ISSUE TITLE
Support for response descriptions

### ISSUE THREAD

**Issue by codebender** [subosito/snowboard#6]
Hi @subosito,

It looks like Apiary's Drafter supports Response Descriptions (https://github.com/apiaryio/drafter/blob/master/features/fixtures/blueprint.apib#L77).  Perhaps snowboard should as well.

Example:
```apib
##  Objects [/objects]
### Create an object [POST]
  Creates an object with the given data

  + Response 200 (application/json)

    Successful Response with the created object

  + Response 422 (application/json)

    Error Response when the object failed validation
```

I was hoping that I would just be able to add this line to a custom template, 
`<div class="description">{{$transition.Response.Description | markdownize}}</div>`
But then I quickly realized that `Description` isn't implemented on the `Response` struct (https://github.com/subosito/snowboard/blob/master/api/blueprint.go#L59-L64). I would create a PR but my GO skills are n00b at best.

I can make an attempt to create a PR if you have no time or interest in implementing this feature.  Tell me what you think.

Cheers! 😸

**Comment by subosito** [comment]
Hi @codebender,

Just pushed changes related to this issue, you can see https://github.com/subosito/snowboard/commit/c8fb717bf9c8d803b0be5acbce713991432d6731.

Please let me know your thoughts :)

**Comment by codebender** [comment]
@subosito Awesome, that was way too quick! Much Appreciated! 

Closing this issue.
