### ISSUE TITLE
Installation failes (Ubuntu 15.10)

### ISSUE THREAD

**Issue by tim-peters** [subosito/snowboard#9]
Unfortunately I'm unable to install this application. Here is what my terminal returns when I do `make install`

```
make install
git submodule update --init --recursive
make -C drafter/ext/drafter drafter
make[1]: Entering directory '/home/tim/Schreibtisch/Make-Cities-Smart-Again-API/snowboard/drafter/ext/drafter'
make -C ./build V=1 drafter
make[2]: Entering directory '/home/tim/Schreibtisch/Make-Cities-Smart-Again-API/snowboard/drafter/ext/drafter/build'
make[2]: Nothing to be done for 'drafter'.
make[2]: Leaving directory '/home/tim/Schreibtisch/Make-Cities-Smart-Again-API/snowboard/drafter/ext/drafter/build'
mkdir -p ./bin
cp -f ./build/out/Release/drafter ./bin/drafter
make[1]: Leaving directory '/home/tim/Schreibtisch/Make-Cities-Smart-Again-API/snowboard/drafter/ext/drafter'
package github.com/mjibson/esc: mkdir /go: permission denied
Makefile:8: recipe for target 'go-gen' failed
make: *** [go-gen] Error 1
```

I have all dependencies installed. Here is my `go env`

´´´
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build915995558=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
´´´

Can anyone tell me what I'm doing wrong?

**Comment by subosito** [comment]
Hi @tim-peters, looks like you don't have enough permission on your `GOPATH`. Please ensure you can go get, for example, `go get github.com/mjibson/esc`. If that's works then `make install` will be ok.

Please let me know if you still have any issue.
